application:
  subdomain: cloudfalredweb
  background_task: true
  routes:
    - /=http://host.lzcapp:14333/
services:
  cloudflaredweb:
    network_mode: host
    # wisdomsky/cloudflared-web:2026.2.0
    # upstream: wisdomsky/cloudflared-web:2026.7.1
    image: registry.lazycat.cloud/czyt/wisdomsky/cloudflared-web:d6e3bde3073ebfab
    binds:
      - /lzcapp/var/config:/config
    environment:
      - PROTOCOL={{.U.protocol}}
