zc-sdk-version: "0.1"
name: Cloudflared(持续更新)
package: cloud.lazycat.app.cloudfalredweb
version: 2025.6.1
description: Cloudflare Tunnel 提供了一种安全的方式，可以将 Web
  服务器安全地公开到互联网上，而无需打开防火墙端口和配置访问控制列表（ACL）。Cloudflare Tunnel 还确保请求在到达 Web 服务器之前通过
  Cloudflare 路由，因此您可以确保攻击流量会被 Cloudflare 的 WAF 和无限制的 DDoS 缓解功能阻止，并在启用了这些功能的情况下通过
  Access 进行身份验证。
homepage: https://github.com/WisdomSky/Cloudflared-web
author: WisdomSky
application:
  subdomain: cloudfalredweb
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://cloudflaredweb.cloud.lazycat.app.cloudfalredweb.lzcapp:14333/
services:
  cloudflaredweb:
    network_mode: host
    # wisdomsky/cloudflared-web:2025.6.1
    image: r registry.lazycat.cloud/czyt/wisdomsky/cloudflared-web:da14181b57e3455b
    binds:
      - /lzcapp/var/config:/config
    environment:
      - PROTOCOL=http2
